# Generated by Django 4.1.3 on 2022-11-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.CharField(default='', max_length=255),
        ),
    ]
